// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAPI(api: any): Promise<any> {
  return window['go']['main']['App']['CreateAPI'](api);
}

export function CreateSchedule(schedule: any): Promise<any> {
  return window['go']['main']['App']['CreateSchedule'](schedule);
}

export function DeleteAPI(id: number): Promise<void> {
  return window['go']['main']['App']['DeleteAPI'](id);
}

export function DeleteSchedule(id: number): Promise<void> {
  return window['go']['main']['App']['DeleteSchedule'](id);
}

export function ExecuteAPIManually(id: number): Promise<void> {
  return window['go']['main']['App']['ExecuteAPIManually'](id);
}

export function GetAPIByID(id: number): Promise<any> {
  return window['go']['main']['App']['GetAPIByID'](id);
}

export function GetAllAPIs(): Promise<any[]> {
  return window['go']['main']['App']['GetAllAPIs']();
}

export function GetAllExecutionLogs(page: number, pageSize: number): Promise<any[]> {
  return window['go']['main']['App']['GetAllExecutionLogs'](page, pageSize);
}

export function GetAllSchedules(): Promise<any[]> {
  return window['go']['main']['App']['GetAllSchedules']();
}

export function GetExecutionLogsByAPIID(id: number, limit: number): Promise<any[]> {
  return window['go']['main']['App']['GetExecutionLogsByAPIID'](id, limit);
}

export function GetRecentExecutions(limit: number): Promise<any[]> {
  return window['go']['main']['App']['GetRecentExecutions'](limit);
}

export function GetSchedulesByAPIID(id: number): Promise<any[]> {
  return window['go']['main']['App']['GetSchedulesByAPIID'](id);
}

export function ToggleSchedule(id: number, active: boolean): Promise<void> {
  return window['go']['main']['App']['ToggleSchedule'](id, active);
}

export function UpdateAPI(api: any): Promise<any> {
  return window['go']['main']['App']['UpdateAPI'](api);
}

export function UpdateSchedule(schedule: any): Promise<void> {
  return window['go']['main']['App']['UpdateSchedule'](schedule);
} 