// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAPI(arg1) {
  return window['go']['main']['App']['CreateAPI'](arg1);
}

export function CreateSchedule(arg1) {
  return window['go']['main']['App']['CreateSchedule'](arg1);
}

export function DeleteAPI(arg1) {
  return window['go']['main']['App']['DeleteAPI'](arg1);
}

export function DeleteSchedule(arg1) {
  return window['go']['main']['App']['DeleteSchedule'](arg1);
}

export function ExecuteAPIManually(arg1) {
  return window['go']['main']['App']['ExecuteAPIManually'](arg1);
}

export function GetAPIByID(arg1) {
  return window['go']['main']['App']['GetAPIByID'](arg1);
}

export function GetAllAPIs() {
  return window['go']['main']['App']['GetAllAPIs']();
}

export function GetAllExecutionLogs(arg1, arg2) {
  return window['go']['main']['App']['GetAllExecutionLogs'](arg1, arg2);
}

export function GetAllSchedules() {
  return window['go']['main']['App']['GetAllSchedules']();
}

export function GetExecutionLogsByAPIID(arg1, arg2) {
  return window['go']['main']['App']['GetExecutionLogsByAPIID'](arg1, arg2);
}

export function GetRecentExecutions(arg1) {
  return window['go']['main']['App']['GetRecentExecutions'](arg1);
}

export function GetSchedulesByAPIID(arg1) {
  return window['go']['main']['App']['GetSchedulesByAPIID'](arg1);
}

export function ToggleSchedule(arg1, arg2) {
  return window['go']['main']['App']['ToggleSchedule'](arg1, arg2);
}

export function UpdateAPI(arg1) {
  return window['go']['main']['App']['UpdateAPI'](arg1);
}

export function UpdateSchedule(arg1) {
  return window['go']['main']['App']['UpdateSchedule'](arg1);
}
