// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSchedule(arg1) {
  return window['go']['main']['App']['CancelSchedule'](arg1);
}

export function CreateAPI(arg1) {
  return window['go']['main']['App']['CreateAPI'](arg1);
}

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateSchedule(arg1) {
  return window['go']['main']['App']['CreateSchedule'](arg1);
}

export function DeleteAPI(arg1) {
  return window['go']['main']['App']['DeleteAPI'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteSchedule(arg1) {
  return window['go']['main']['App']['DeleteSchedule'](arg1);
}

export function ExecuteAPIManually(arg1) {
  return window['go']['main']['App']['ExecuteAPIManually'](arg1);
}

export function GetAPIAnalytics(arg1) {
  return window['go']['main']['App']['GetAPIAnalytics'](arg1);
}

export function GetAPIByID(arg1) {
  return window['go']['main']['App']['GetAPIByID'](arg1);
}

export function GetAPIsByCollectionID(arg1) {
  return window['go']['main']['App']['GetAPIsByCollectionID'](arg1);
}

export function GetAllAPIs() {
  return window['go']['main']['App']['GetAllAPIs']();
}

export function GetAllCollections() {
  return window['go']['main']['App']['GetAllCollections']();
}

export function GetAllExecutionLogs(arg1, arg2) {
  return window['go']['main']['App']['GetAllExecutionLogs'](arg1, arg2);
}

export function GetAllSchedules() {
  return window['go']['main']['App']['GetAllSchedules']();
}

export function GetCollectionByID(arg1) {
  return window['go']['main']['App']['GetCollectionByID'](arg1);
}

export function GetExecutionLogsByAPIID(arg1, arg2) {
  return window['go']['main']['App']['GetExecutionLogsByAPIID'](arg1, arg2);
}

export function GetExecutionStatusCounts(arg1) {
  return window['go']['main']['App']['GetExecutionStatusCounts'](arg1);
}

export function GetOverallAnalytics() {
  return window['go']['main']['App']['GetOverallAnalytics']();
}

export function GetRecentExecutions(arg1) {
  return window['go']['main']['App']['GetRecentExecutions'](arg1);
}

export function GetSchedulesByAPIID(arg1) {
  return window['go']['main']['App']['GetSchedulesByAPIID'](arg1);
}

export function ToggleSchedule(arg1, arg2) {
  return window['go']['main']['App']['ToggleSchedule'](arg1, arg2);
}

export function UpdateAPI(arg1) {
  return window['go']['main']['App']['UpdateAPI'](arg1);
}

export function UpdateCollection(arg1) {
  return window['go']['main']['App']['UpdateCollection'](arg1);
}

export function UpdateSchedule(arg1) {
  return window['go']['main']['App']['UpdateSchedule'](arg1);
}
